-- Insert all remaining questions from sections 2-7 (fixed syntax)
-- Section 2: Financial & Regulatory
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, score_map, helper) VALUES
('F1', 'ai_readiness_v2', 'section_2', 'What is your current monthly budget for AI and data initiatives?', 'select', 1, true, '["< €100", "€100–500", "€500–2 000", "€2 000–15 000", "Over €15 000"]'::jsonb, '[0,25,50,75,100]'::jsonb, NULL),
('F3', 'ai_readiness_v2', 'section_2', 'How long can you fund your AI and data efforts without new investment or revenue?', 'select', 2, true, '["Less than 3 months", "3–6 months", "6–12 months", "12–24 months", "Over 24 months"]'::jsonb, '[0,25,50,75,100]'::jsonb, 'Indicates financial runway for AI projects.'),
('F4', 'ai_readiness_v2', 'section_2', 'How supportive are your board or investors of your AI initiatives?', 'select', 3, true, '["Not supportive", "Discussion only, no commitments", "Open to AI initiatives", "Budget approved", "Active championing"]'::jsonb, '[0,25,50,75,100]'::jsonb, NULL),
('F5', 'ai_readiness_v2', 'section_2', 'Which additional regulatory or security frameworks apply to your organization?', 'multi_select', 4, true, '["MiFID II / MDR – Finance & medical (EU)", "ISO 27001 – Information security", "PCI-DSS – Payment data security", "HIPAA – US health data", "CCPA – California privacy", "LGPD – Brazilian privacy", "POPIA – South African privacy", "None apply"]'::jsonb, NULL, 'GDPR and EU AI Act apply by default.'),
('F6', 'ai_readiness_v2', 'section_2', 'What level of strategic partnerships do you have for AI?', 'select', 5, true, '["None", "Exploratory discussions", "One active partnership", "Multiple partnerships", "Ecosystem collaboration (R&D + vendors)"]'::jsonb, '[0,25,50,75,100]'::jsonb, 'Choose the option that best describes your existing AI partnership activity.'),
('F7', 'ai_readiness_v2', 'section_2', 'What percentage of your AI budget is allocated to ethics and bias mitigation?', 'select', 6, true, '["None", "Planned next fiscal year", "Under 5 %", "5–15 %", "Over 15 %"]'::jsonb, '[0,25,50,75,100]'::jsonb, NULL);

-- Section 3: Data Foundation
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, helper) VALUES
('D1', 'ai_readiness_v2', 'section_3', 'Where is your most critical data primarily stored?', 'multi_select', 1, true, '["Files & spreadsheets (e.g. Excel, Google Sheets, local files)", "Databases (e.g. SQL, NoSQL, data warehouses)", "Cloud & SaaS platforms (e.g. Google Drive, Salesforce, HubSpot)", "Internal tools / legacy systems (e.g. custom apps, intranet)", "Analytics & BI platforms (e.g. Power BI, Looker, Tableau)"]'::jsonb, 'Critical data drives operations, decisions, and compliance.'),
('D2', 'ai_readiness_v2', 'section_3', 'How much data does your organization generate or collect each month?', 'select', 2, true, '["Don''t know", "< 1 GB", "1–10 GB", "10–100 GB", "> 100 GB"]'::jsonb, NULL),
('D3', 'ai_readiness_v2', 'section_3', 'How mature is your data management (structure, tools, and lineage)?', 'select', 3, true, '["No standards or visibility", "Basic naming conventions & partial docs", "Defined standards with manual processes", "Schema tools & automated tracking for key systems", "Version-controlled models with full lineage & governance"]'::jsonb, NULL),
('D4', 'ai_readiness_v2', 'section_3', 'How confident are you in the accuracy and freshness of your critical data?', 'select', 4, true, '["Low – data often outdated or unreliable", "Medium – manual checks for accuracy", "High – periodic data quality tests", "Very high – automated alerts for data issues", "Excellent – real-time monitoring & validation"]'::jsonb, NULL),
('D5', 'ai_readiness_v2', 'section_3', 'Which security controls protect your data infrastructure?', 'multi_select', 5, true, '["Encryption at rest (e.g. data encrypted on AWS S3 or Azure Blob Storage)", "TLS/HTTPS in transit (e.g. API calls over HTTPS)", "Role-based access controls (e.g. Google Cloud IAM, Azure RBAC)", "Audit logs & monitoring (e.g. AWS CloudTrail, GCP Stackdriver)", "Data Loss Prevention (DLP) (e.g. Google Cloud DLP, Azure Purview)", "Tokenization (e.g. Vault-based tokenization of sensitive fields)", "Differential privacy (e.g. noise injection for analytics)", "None", "I don''t know", "Other (please specify)"]'::jsonb, 'Security controls are measures that keep your data safe—encrypting it, controlling access, and monitoring usage.'),
('D6', 'ai_readiness_v2', 'section_3', 'How is data stewardship and cleaning managed?', 'select', 6, true, '["No owner", "Occasional clean-ups", "Assigned owner with periodic review", "Dedicated steward with monthly routines", "Continuous stewardship and monitoring"]'::jsonb, NULL),
('D7', 'ai_readiness_v2', 'section_3', 'How prepared are you for GDPR or EU AI Act audits?', 'select', 7, true, '["Not prepared", "Basic documentation", "Regular compliance checks", "Audit-ready with documentation", "Continuous compliance monitoring"]'::jsonb, NULL);

-- Section 4: Tools & Infrastructure  
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, score_map) VALUES
('T1', 'ai_readiness_v2', 'section_4', 'Which AI/ML platforms or tools does your organization currently use?', 'multi_select', 1, true, '["ChatGPT / OpenAI APIs", "Microsoft Copilot", "Google Gemini / Vertex AI", "Amazon Bedrock / SageMaker", "Anthropic Claude", "Custom models (open source)", "Industry-specific AI tools", "No AI tools currently", "Other"]'::jsonb, NULL),
('T2', 'ai_readiness_v2', 'section_4', 'How would you describe your current technical infrastructure?', 'select', 2, true, '["Basic cloud or on-premise setup", "Managed cloud services", "Scalable cloud with some automation", "Advanced cloud with CI/CD", "Enterprise-grade with full DevOps"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('T3', 'ai_readiness_v2', 'section_4', 'What is your primary development environment?', 'select', 3, true, '["Local development only", "Cloud-based notebooks", "Version-controlled repositories", "Integrated dev/staging/prod", "MLOps pipeline with automation"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('T4', 'ai_readiness_v2', 'section_4', 'How do you manage model versioning and deployment?', 'select', 4, true, '["No formal process", "Manual versioning", "Git-based versioning", "Automated CI/CD for models", "Full MLOps with monitoring"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('T5', 'ai_readiness_v2', 'section_4', 'What monitoring capabilities do you have for AI systems?', 'select', 5, true, '["No monitoring", "Basic logging", "Performance dashboards", "Automated alerting", "Full observability stack"]'::jsonb, '[0,25,50,75,100]'::jsonb);

-- Section 5: Automation & Processes
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, score_map) VALUES
('A1', 'ai_readiness_v2', 'section_5', 'How mature are your current business processes?', 'select', 1, true, '["Ad hoc and informal", "Some documentation", "Standardized processes", "Optimized workflows", "Continuous improvement culture"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('A2', 'ai_readiness_v2', 'section_5', 'What percentage of your key processes are currently automated?', 'select', 2, true, '["0-10%", "10-25%", "25-50%", "50-75%", "75%+"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('A3', 'ai_readiness_v2', 'section_5', 'How do you approach process improvement?', 'select', 3, true, '["Reactive to problems", "Annual reviews", "Quarterly assessments", "Continuous monitoring", "Predictive optimization"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('A4', 'ai_readiness_v2', 'section_5', 'What automation tools do you currently use?', 'multi_select', 4, true, '["Zapier/IFTTT", "Microsoft Power Automate", "Custom scripts", "RPA tools (UiPath, etc.)", "Workflow management systems", "None"]'::jsonb, NULL),
('A5', 'ai_readiness_v2', 'section_5', 'How ready are your processes for AI integration?', 'select', 5, true, '["Would require major changes", "Some adaptation needed", "Minor modifications required", "Ready with minimal changes", "Already optimized for AI"]'::jsonb, '[0,25,50,75,100]'::jsonb);

-- Section 6: People & Skills
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, score_map) VALUES
('P1', 'ai_readiness_v2', 'section_6', 'How would you rate your organization''s overall AI literacy?', 'select', 1, true, '["Very low", "Low", "Medium", "High", "Very high"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('P2', 'ai_readiness_v2', 'section_6', 'Which AI-related skills exist in your organization?', 'multi_select', 2, true, '["Data analysis", "Machine learning", "AI strategy", "Data engineering", "MLOps", "AI ethics", "Prompt engineering", "None of the above"]'::jsonb, NULL),
('P3', 'ai_readiness_v2', 'section_6', 'How does your organization approach AI training?', 'select', 3, true, '["No formal training", "Ad hoc learning", "Structured training programs", "Continuous learning culture", "AI Centers of Excellence"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('P4', 'ai_readiness_v2', 'section_6', 'What is your biggest challenge in AI talent acquisition?', 'select', 4, true, '["No budget for AI talent", "Can''t find qualified candidates", "Competition for talent", "Lack of clear role definitions", "No significant challenges"]'::jsonb, NULL),
('P5', 'ai_readiness_v2', 'section_6', 'How prepared is your workforce for AI-driven changes?', 'select', 5, true, '["Resistant to change", "Cautiously open", "Neutral", "Enthusiastic", "Driving the change"]'::jsonb, '[0,25,50,75,100]'::jsonb);

-- Section 7: Governance & Ethics
INSERT INTO questions (id, assessment_id, section_id, text, type, sequence, required, options, score_map) VALUES
('G1', 'ai_readiness_v2', 'section_7', 'Do you have formal AI governance policies?', 'select', 1, true, '["No policies", "Draft policies", "Basic policies in place", "Comprehensive governance framework", "Advanced governance with oversight"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('G2', 'ai_readiness_v2', 'section_7', 'How do you address AI bias and fairness?', 'select', 2, true, '["Not addressed", "Awareness only", "Basic guidelines", "Testing procedures", "Continuous monitoring"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('G3', 'ai_readiness_v2', 'section_7', 'What AI risk management practices do you have?', 'multi_select', 3, true, '["Risk assessment frameworks", "Regular audits", "Incident response plans", "Model validation", "Third-party assessments", "None"]'::jsonb, NULL),
('G4', 'ai_readiness_v2', 'section_7', 'How transparent are your AI systems to stakeholders?', 'select', 4, true, '["No transparency", "Limited disclosure", "Basic explanations", "Detailed documentation", "Full transparency with audit trails"]'::jsonb, '[0,25,50,75,100]'::jsonb),
('G5', 'ai_readiness_v2', 'section_7', 'Who is responsible for AI ethics in your organization?', 'select', 5, true, '["No designated owner", "IT department", "Legal/Compliance team", "Dedicated AI ethics officer", "Ethics committee"]'::jsonb, '[0,25,50,75,100]'::jsonb);