-- Create questions table
CREATE TABLE IF NOT EXISTS questions (
  id text PRIMARY KEY,
  assessment_id text NOT NULL,
  section_id text NOT NULL,
  text text NOT NULL,
  type text NOT NULL,
  helper text,
  options jsonb,
  show_if jsonb,
  required boolean DEFAULT true,
  sequence integer NOT NULL,
  score_map jsonb,
  score_per integer,
  cap integer,
  weight jsonb,
  max_rank integer,
  score_by_count jsonb,
  score_formula text,
  max_select integer,
  rows jsonb,
  columns jsonb,
  groups jsonb,
  hide_if jsonb,
  is_add_on boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access
CREATE POLICY "Everyone can read questions" ON questions FOR SELECT USING (true);

-- Clear existing questions and insert all 87 questions
DELETE FROM questions;

INSERT INTO questions (
  id, assessment_id, section_id, text, type, helper, options, show_if, required, sequence, 
  score_map, score_per, cap, weight, max_rank, score_by_count, score_formula, 
  max_select, rows, columns, groups, hide_if, is_add_on
) VALUES
-- Section 0: Organization Profile (M0-M7_revenue)
('M0', 'ai-readiness-assessment', 'section_0', 'Organization name', 'text', NULL, NULL, NULL, true, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M1', 'ai-readiness-assessment', 'section_0', 'Full name', 'text', NULL, NULL, NULL, true, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M2', 'ai-readiness-assessment', 'section_0', 'Business e-mail', 'email', NULL, NULL, NULL, true, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M3', 'ai-readiness-assessment', 'section_0', 'Primary role', 'single', NULL, '["CEO/Founder", "CTO/CIO", "Data/AI Lead", "Product Manager", "Operations Manager", "Other"]'::jsonb, NULL, true, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M4_industry', 'ai-readiness-assessment', 'section_0', 'Industry & sub-sector', 'industry_dropdown', NULL, NULL, NULL, true, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M5_country', 'ai-readiness-assessment', 'section_0', 'Country', 'dropdown', NULL, NULL, NULL, true, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M6_size', 'ai-readiness-assessment', 'section_0', 'Company size (FTE)', 'single', NULL, '["1-10", "11-50", "51-200", "201-1000", "1000+"]'::jsonb, NULL, true, 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('M7_revenue', 'ai-readiness-assessment', 'section_0', 'Annual revenue', 'single', NULL, '["<$1M", "$1M-$10M", "$10M-$100M", "$100M-$1B", "$1B+"]'::jsonb, NULL, true, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 1: Strategy & Use-Case Readiness (S1-S12)
('S1', 'ai-readiness-assessment', 'section_1', 'How many AI use cases have you identified for implementation within the next 12 months?', 'single', NULL, '["0", "1-3", "4-10", "11-25", "25+"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S2', 'ai-readiness-assessment', 'section_1', 'How do you decide which AI opportunities to pursue first?', 'single', NULL, '["No formal process", "Ad-hoc discussions", "Basic cost-benefit analysis", "Structured evaluation framework", "Advanced portfolio optimization"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S3', 'ai-readiness-assessment', 'section_1', 'How integrated are your AI performance metrics with corporate KPIs or OKRs?', 'single', NULL, '["Not integrated", "Loosely connected", "Some alignment", "Well integrated", "Fully integrated"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S4', 'ai-readiness-assessment', 'section_1', 'How do you estimate ROI for AI projects?', 'single', NULL, '["No ROI estimation", "Basic cost savings", "Revenue impact modeling", "Comprehensive business case", "Dynamic value tracking"]'::jsonb, NULL, true, 4, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S5', 'ai-readiness-assessment', 'section_1', 'What is your typical time from idea to measurable AI impact?', 'single', NULL, '["Not measured", "12+ months", "6-12 months", "3-6 months", "Under 3 months"]'::jsonb, NULL, true, 5, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S6', 'ai-readiness-assessment', 'section_1', 'How do you monitor competitor or industry AI developments?', 'single', NULL, '["No monitoring", "Occasional news", "Industry reports", "Regular competitive analysis", "Systematic intelligence"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S7', 'ai-readiness-assessment', 'section_1', 'Rank your top four strategic objectives for AI initiatives', 'rank', NULL, '["Cost reduction", "Revenue growth", "Customer experience", "Operational efficiency", "Innovation/R&D", "Risk management", "Competitive advantage"]'::jsonb, NULL, true, 7, NULL, NULL, NULL, NULL, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S8', 'ai-readiness-assessment', 'section_1', 'How aligned is your leadership team on AI strategy?', 'single', NULL, '["No alignment", "Some interest", "General agreement", "Strong alignment", "Unified vision"]'::jsonb, NULL, true, 8, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S9', 'ai-readiness-assessment', 'section_1', 'Which teams are involved in defining AI use cases?', 'multi', NULL, '["IT/Technology", "Data/Analytics", "Product", "Operations", "Sales/Marketing", "Finance", "HR", "Legal/Compliance"]'::jsonb, NULL, true, 9, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S10', 'ai-readiness-assessment', 'section_1', 'How prepared is your organization to manage change from AI adoption?', 'single', NULL, '["Not prepared", "Minimal preparation", "Some planning", "Well prepared", "Change management experts"]'::jsonb, NULL, true, 10, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S11', 'ai-readiness-assessment', 'section_1', 'How clear are the goals and metrics for your AI use cases?', 'single', NULL, '["No clear goals", "Vague objectives", "Some defined metrics", "Clear measurable goals", "Comprehensive KPI framework"]'::jsonb, NULL, true, 11, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('S12', 'ai-readiness-assessment', 'section_1', 'What best describes your approach to piloting and deploying AI projects?', 'single', NULL, '["No formal approach", "Ad-hoc pilots", "Structured pilot process", "Agile deployment methodology", "Continuous delivery pipeline"]'::jsonb, NULL, true, 12, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 2: Budget, Runway & Compliance (F1, F3-F8)
('F1', 'ai-readiness-assessment', 'section_2', 'What is your current monthly budget for AI and data initiatives?', 'single', NULL, '["No dedicated budget", "Under $10K", "$10K-$50K", "$50K-$200K", "$200K+"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F3', 'ai-readiness-assessment', 'section_2', 'How long can you fund your AI and data efforts without new investment or revenue?', 'single', NULL, '["Less than 6 months", "6-12 months", "1-2 years", "2-3 years", "3+ years"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F4', 'ai-readiness-assessment', 'section_2', 'How supportive are your board or investors of your AI initiatives?', 'single', NULL, '["Not supportive", "Neutral/skeptical", "Somewhat supportive", "Very supportive", "AI champions"]'::jsonb, NULL, true, 4, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F5', 'ai-readiness-assessment', 'section_2', 'Which additional regulatory or security frameworks apply to your organization?', 'multi', NULL, '["GDPR", "HIPAA", "SOX", "PCI DSS", "ISO 27001", "SOC 2", "FedRAMP", "Industry-specific regulations", "None"]'::jsonb, NULL, true, 5, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F6', 'ai-readiness-assessment', 'section_2', 'What level of strategic partnerships do you have for AI?', 'single', NULL, '["No partnerships", "Vendor relationships", "Some strategic alliances", "Multiple partnerships", "Ecosystem leadership"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F7', 'ai-readiness-assessment', 'section_2', 'What percentage of your AI budget is allocated to ethics and bias mitigation?', 'single', NULL, '["0%", "1-5%", "6-10%", "11-20%", "20%+"]'::jsonb, NULL, true, 7, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('F8', 'ai-readiness-assessment', 'section_2', 'Which mechanisms do you use for cross-border data transfers?', 'multi', NULL, '["Standard Contractual Clauses (SCCs)", "Binding Corporate Rules (BCRs)", "Adequacy decisions", "Derogations", "Local data residency", "None/Not applicable"]'::jsonb, '{"track": ["REG"]}'::jsonb, true, 8, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 3: Data Foundation & Security (D1-D10)
('D1', 'ai-readiness-assessment', 'section_3', 'Where is your most critical data primarily stored?', 'single', NULL, '["Local servers", "Cloud (single provider)", "Multi-cloud", "Hybrid cloud", "Distributed/federated"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D2', 'ai-readiness-assessment', 'section_3', 'How much data does your organization generate or collect each month?', 'single', NULL, '["Less than 1GB", "1GB-100GB", "100GB-1TB", "1TB-10TB", "10TB+"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D3', 'ai-readiness-assessment', 'section_3', 'How mature is your data management (structure, tools, and lineage)?', 'single', NULL, '["Ad-hoc/manual", "Basic tools", "Some automation", "Well-structured", "Fully automated"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D4', 'ai-readiness-assessment', 'section_3', 'How confident are you in the accuracy and freshness of your critical data?', 'single', NULL, '["Low confidence", "Some concerns", "Generally confident", "High confidence", "Completely confident"]'::jsonb, NULL, true, 4, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D5', 'ai-readiness-assessment', 'section_3', 'Which security controls protect your data infrastructure?', 'multi', NULL, '["Encryption at rest", "Encryption in transit", "Access controls", "Audit logging", "Data loss prevention", "Multi-factor authentication", "Regular security testing", "None"]'::jsonb, NULL, true, 5, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D6', 'ai-readiness-assessment', 'section_3', 'How is data stewardship and cleaning managed?', 'single', NULL, '["Manual/ad-hoc", "Basic processes", "Some automation", "Well-defined workflows", "Fully automated"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D7', 'ai-readiness-assessment', 'section_3', 'How prepared are you for GDPR or EU AI Act audits?', 'single', NULL, '["Not prepared", "Basic awareness", "Some documentation", "Well prepared", "Audit-ready"]'::jsonb, '{"track": ["REG"]}'::jsonb, true, 7, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D8', 'ai-readiness-assessment', 'section_3', 'How mature is your data labeling and annotation process?', 'single', NULL, '["No process", "Manual labeling", "Some tools", "Automated with review", "Fully automated"]'::jsonb, NULL, true, 8, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D9', 'ai-readiness-assessment', 'section_3', 'Do you use synthetic or third-party data to augment your datasets?', 'single', NULL, '["No", "Considering", "Limited use", "Regular use", "Extensive use"]'::jsonb, NULL, true, 9, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('D10', 'ai-readiness-assessment', 'section_3', 'How developed are your AI ethics and data privacy policies?', 'single', NULL, '["No policies", "Basic guidelines", "Some formal policies", "Comprehensive policies", "Industry-leading framework"]'::jsonb, NULL, true, 10, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 4: Tool Stack & Integration (T0_tools, T1-T9)
('T0_tools', 'ai-readiness-assessment', 'section_4', 'Which tools are actively used by you and your team?', 'multi', NULL, '["Excel/Sheets", "Business Intelligence tools", "Database systems", "Cloud platforms", "AI/ML platforms", "Data pipeline tools", "Version control", "Collaboration tools"]'::jsonb, NULL, true, 0, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T1', 'ai-readiness-assessment', 'section_4', 'How well are your tools and systems connected?', 'single', NULL, '["Not connected", "Manual connections", "Some automation", "Well integrated", "Fully automated"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T2', 'ai-readiness-assessment', 'section_4', 'How often do data connections fail or cause issues?', 'single', NULL, '["Daily", "Weekly", "Monthly", "Rarely", "Never"]'::jsonb, NULL, true, 2, '[100, 75, 50, 25, 0]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T3', 'ai-readiness-assessment', 'section_4', 'Who owns and maintains your system integrations?', 'single', NULL, '["No one", "Individual contributors", "Small team", "Dedicated team", "External partners"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T4', 'ai-readiness-assessment', 'section_4', 'How well are you connected to external AI services and LLMs?', 'single', NULL, '["Not connected", "Basic API access", "Some integrations", "Well connected", "Strategic partnerships"]'::jsonb, NULL, true, 4, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T5', 'ai-readiness-assessment', 'section_4', 'What access do you have to GPU/TPU compute?', 'single', NULL, '["No access", "Cloud on-demand", "Some dedicated", "Substantial resources", "Enterprise-grade"]'::jsonb, NULL, true, 5, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T6', 'ai-readiness-assessment', 'section_4', 'How well is your technical or data architecture documented?', 'single', NULL, '["Not documented", "Basic documentation", "Some documentation", "Well documented", "Comprehensive docs"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T7', 'ai-readiness-assessment', 'section_4', 'What level of disaster recovery planning exists for data & AI?', 'single', NULL, '["No planning", "Basic backups", "Some planning", "Comprehensive plan", "Tested & verified"]'::jsonb, NULL, true, 7, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T8', 'ai-readiness-assessment', 'section_4', 'Which low-code or no-code platforms do you use for automation?', 'multi', NULL, '["Zapier", "Microsoft Power Platform", "Google Apps Script", "Airtable", "Notion", "Custom solutions", "None"]'::jsonb, NULL, true, 8, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('T9', 'ai-readiness-assessment', 'section_4', 'How do you deploy ML models and monitor them in production?', 'single', NULL, '["No deployment", "Manual process", "Basic automation", "CI/CD pipeline", "MLOps platform"]'::jsonb, '{"track": ["TECH"]}'::jsonb, true, 9, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 5: Automation & AI Agents (A1-A11)
('A1', 'ai-readiness-assessment', 'section_5', 'Which three tasks would most benefit from automation in your organization?', 'multi', NULL, '["Data entry", "Report generation", "Customer service", "Email management", "Scheduling", "Inventory management", "Quality control", "Financial processing", "Content creation", "Decision support"]'::jsonb, NULL, true, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, false),
('A2', 'ai-readiness-assessment', 'section_5', 'How mature are your current automation efforts?', 'single', NULL, '["No automation", "Basic scripts", "Some workflows", "Significant automation", "Fully automated"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A3', 'ai-readiness-assessment', 'section_5', 'What is the current status of AI agents in your operations?', 'single', NULL, '["Not using", "Exploring", "Piloting", "Limited deployment", "Widespread use"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A4', 'ai-readiness-assessment', 'section_5', 'Which tasks are you considering for AI-agent automation?', 'multi', NULL, '["Customer support", "Data analysis", "Content generation", "Process optimization", "Monitoring & alerts", "Decision making", "Research & insights", "Quality assurance"]'::jsonb, NULL, true, 4, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A5', 'ai-readiness-assessment', 'section_5', 'What level of autonomy do you want for your AI agents?', 'single', NULL, '["Human approval required", "Supervised operation", "Semi-autonomous", "Mostly autonomous", "Fully autonomous"]'::jsonb, NULL, true, 5, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A6', 'ai-readiness-assessment', 'section_5', 'How do you monitor and alert on your automated processes?', 'single', NULL, '["No monitoring", "Basic logging", "Some dashboards", "Comprehensive monitoring", "Predictive alerting"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A7', 'ai-readiness-assessment', 'section_5', 'What are the main blockers to automating tasks and deploying AI agents?', 'multi', NULL, '["Technical complexity", "Budget constraints", "Lack of expertise", "Data quality issues", "Security concerns", "Regulatory compliance", "Change resistance", "Integration challenges"]'::jsonb, NULL, true, 7, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A8', 'ai-readiness-assessment', 'section_5', 'Which interface do you prefer for interacting with AI agents?', 'single', NULL, '["Chat/conversational", "Dashboard/GUI", "API/programmatic", "Voice interface", "Mixed interfaces"]'::jsonb, NULL, true, 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A9', 'ai-readiness-assessment', 'section_5', 'What governance processes do you have for AI agents?', 'single', NULL, '["No governance", "Basic guidelines", "Some processes", "Formal governance", "Comprehensive framework"]'::jsonb, NULL, true, 9, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A10', 'ai-readiness-assessment', 'section_5', 'What recovery or rollback strategy exists for failed automations or AI agents?', 'single', NULL, '["No strategy", "Manual intervention", "Basic rollback", "Automated recovery", "Comprehensive disaster recovery"]'::jsonb, NULL, true, 10, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('A11', 'ai-readiness-assessment', 'section_5', 'How do you track the accuracy and quality of AI agent outputs?', 'single', NULL, '["No tracking", "Manual review", "Basic metrics", "Comprehensive tracking", "Real-time quality assurance"]'::jsonb, NULL, true, 11, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 6: Team Capability & Culture (C1-C11)
('C1', 'ai-readiness-assessment', 'section_6', 'How often do you and your team use AI tools in your daily work?', 'single', NULL, '["Never", "Rarely", "Sometimes", "Frequently", "Daily"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C2', 'ai-readiness-assessment', 'section_6', 'How confident are you and your team at these prompt-writing skills?', 'single', NULL, '["No experience", "Basic prompts", "Some skill", "Proficient", "Expert level"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C3', 'ai-readiness-assessment', 'section_6', 'How do you and your team share AI learnings internally?', 'single', NULL, '["No sharing", "Informal discussion", "Regular meetings", "Documentation", "Formal knowledge management"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C3a', 'ai-readiness-assessment', 'section_6', 'Which AI training topics should you and your team prioritize? (Rank top 3)', 'rank', NULL, '["Prompt engineering", "AI ethics & bias", "Data science fundamentals", "ML model development", "AI tool adoption", "Change management", "AI strategy"]'::jsonb, NULL, true, 4, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C4', 'ai-readiness-assessment', 'section_6', 'What annual budget do you and your team allocate per person for AI upskilling?', 'single', NULL, '["$0", "$1-$500", "$501-$2000", "$2001-$5000", "$5000+"]'::jsonb, NULL, true, 5, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C5', 'ai-readiness-assessment', 'section_6', 'How many hours per month can you and your team dedicate to AI training?', 'single', NULL, '["0 hours", "1-5 hours", "6-15 hours", "16-30 hours", "30+ hours"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C6', 'ai-readiness-assessment', 'section_6', 'What format do you and your team prefer for AI training delivery?', 'single', NULL, '["Self-paced online", "Live virtual sessions", "In-person workshops", "Mentoring/coaching", "Mixed approach"]'::jsonb, NULL, true, 7, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C7', 'ai-readiness-assessment', 'section_6', 'How often do you and your team engage external AI experts?', 'single', NULL, '["Never", "Rarely", "Quarterly", "Monthly", "Regularly"]'::jsonb, NULL, true, 8, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C8', 'ai-readiness-assessment', 'section_6', 'What stops you and your team from piloting more AI projects?', 'multi', NULL, '["Lack of time", "Budget constraints", "Technical complexity", "Lack of expertise", "Risk aversion", "Regulatory concerns", "Data quality", "Leadership support"]'::jsonb, NULL, true, 9, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C9', 'ai-readiness-assessment', 'section_6', 'How open are you and your team to piloting new AI projects?', 'single', NULL, '["Very resistant", "Somewhat resistant", "Neutral", "Somewhat open", "Very open"]'::jsonb, NULL, true, 10, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C10', 'ai-readiness-assessment', 'section_6', 'How frequently do you and your team collaborate across functions on AI initiatives?', 'single', NULL, '["Never", "Rarely", "Sometimes", "Frequently", "Always"]'::jsonb, NULL, true, 11, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('C11', 'ai-readiness-assessment', 'section_6', 'How safe do you and your team feel to experiment and fail with AI?', 'single', NULL, '["Very unsafe", "Somewhat unsafe", "Neutral", "Somewhat safe", "Very safe"]'::jsonb, NULL, true, 12, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 7: Governance, Risk & Ethics (G1-G10)
('G1', 'ai-readiness-assessment', 'section_7', 'How mature are your processes for identifying and mitigating AI risks and biases?', 'single', NULL, '["No processes", "Basic awareness", "Some processes", "Mature processes", "Industry-leading"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G2', 'ai-readiness-assessment', 'section_7', 'How well can you explain and audit AI model decisions?', 'single', NULL, '["No explainability", "Basic logging", "Some interpretability", "Good explainability", "Full auditability"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G3', 'ai-readiness-assessment', 'section_7', 'How transparent are you with users and stakeholders about AI use?', 'single', NULL, '["No transparency", "Limited disclosure", "Some transparency", "Clear communication", "Full transparency"]'::jsonb, NULL, true, 3, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G4', 'ai-readiness-assessment', 'section_7', 'What level of incident response planning exists for AI failures or harms?', 'single', NULL, '["No planning", "Basic response", "Some planning", "Comprehensive plan", "Tested & verified"]'::jsonb, NULL, true, 4, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G5', 'ai-readiness-assessment', 'section_7', 'What level of human oversight do you enforce on AI outputs?', 'single', NULL, '["No oversight", "Minimal review", "Regular review", "Comprehensive oversight", "Continuous monitoring"]'::jsonb, NULL, true, 5, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G6', 'ai-readiness-assessment', 'section_7', 'How deeply is privacy built into your AI development process?', 'single', NULL, '["Not considered", "Basic compliance", "Some privacy measures", "Privacy by design", "Privacy leadership"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G7', 'ai-readiness-assessment', 'section_7', 'What is the status of independent audits for your AI systems?', 'single', NULL, '["None – no audits conducted", "Planned – audit scheduled", "In progress – audit underway", "Completed – initial audit done", "Ongoing – regular audit cycle"]'::jsonb, '{"track": ["REG", "TECH"]}'::jsonb, true, 7, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G8', 'ai-readiness-assessment', 'section_7', 'How far along are you in mapping AI risks under the EU AI Act?', 'single', 'Mapping means identifying and documenting risks under EU rules (e.g. creating a risk register of AI use cases).', '["Not aware – haven''t reviewed requirements", "Aware – know obligations but not mapped", "Mapping started – risk register in progress", "Completed – risk register finished", "Reported – findings shared with leadership"]'::jsonb, NULL, true, 8, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G9', 'ai-readiness-assessment', 'section_7', 'How regularly do you test your AI models for fairness?', 'single', NULL, '["Never – no fairness tests", "Ad-hoc – tests only after incidents", "Pre-release – tests before each deployment", "Quarterly – scheduled fairness reviews", "Continuous – automated monitoring"]'::jsonb, '{"track": ["REG", "TECH"]}'::jsonb, true, 9, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('G10', 'ai-readiness-assessment', 'section_7', 'What governance body oversees your AI ethics and compliance?', 'single', 'Governance bodies set and enforce rules—e.g. data‐privacy policies, bias‐review processes, acceptable‐use guidelines. Examples: an internal AI ethics committee that reviews new models, a compliance team enforcing GDPR rules, or an external expert panel.', '["None – no oversight body", "Informal – occasional advisor reviews", "Ad-hoc – project-based ethics reviews", "Scheduled – regular ethics committee meetings", "External – includes independent ethics experts"]'::jsonb, NULL, true, 10, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),

-- Section 8: Implementation Horizon & Vision (P1-P7)
('P1', 'ai-readiness-assessment', 'section_8', 'When do you plan to roll out your AI initiatives?', 'single', NULL, '["No specific timeline", "12+ months", "6-12 months", "3-6 months", "Within 3 months"]'::jsonb, NULL, true, 1, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('P2', 'ai-readiness-assessment', 'section_8', 'What level of risk are you comfortable taking on AI projects?', 'single', NULL, '["Very low risk", "Low risk", "Moderate risk", "High risk", "Very high risk"]'::jsonb, NULL, true, 2, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('P3', 'ai-readiness-assessment', 'section_8', 'Which success metrics are most important for your AI work? (Select up to 3)', 'multi', NULL, '["Cost reduction", "Revenue increase", "Time savings", "Quality improvement", "Customer satisfaction", "Employee productivity", "Innovation metrics", "Risk reduction"]'::jsonb, NULL, true, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, false),
('P4', 'ai-readiness-assessment', 'section_8', 'What is your preferred resource strategy for AI projects?', 'single', NULL, '["Internal team only", "Mostly internal", "Balanced internal/external", "Mostly external", "External partners only"]'::jsonb, NULL, true, 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('P5', 'ai-readiness-assessment', 'section_8', 'Which technology architectures do you prefer for AI solutions? (Select all)', 'multi', NULL, '["Cloud-native", "On-premises", "Hybrid cloud", "Edge computing", "Serverless", "Containerized", "Microservices", "Monolithic"]'::jsonb, NULL, true, 5, NULL, 10, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('P6', 'ai-readiness-assessment', 'section_8', 'What level of external support do you expect for AI implementation?', 'single', NULL, '["No external support", "Minimal consulting", "Some guidance", "Significant support", "Full implementation support"]'::jsonb, NULL, true, 6, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false),
('P7', 'ai-readiness-assessment', 'section_8', 'How significant of an organizational change are you prepared for to adopt AI?', 'single', 'Matches change-management training to readiness level.', '["Minimal changes", "Minor tweaks", "Moderate transformation", "Major transformation", "Continuous evolution"]'::jsonb, NULL, true, 7, '[0, 25, 50, 75, 100]'::jsonb, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, false);