// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ursnkjhyeupfvlnahuyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyc25ramh5ZXVwZnZsbmFodXloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1OTE4OTIsImV4cCI6MjA3MDE2Nzg5Mn0.qqZ3thy2Q5NKARonhDNj4CfCua5slLhRWCqu49eopsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});